<?php
/**
 * Expense related constants
 */

// Hash.
define('HASH_LENGTH_FOR_PROPERLY_EXPENSE', 5);
define('HASH_CHAR_FOR_PROPERLY_EXPENSE', 'A321BCDEFGHIMNOPQRSJKLTUVWXYZ789456');
define('HASH_SALT_FOR_PROPERLY_EXPENSE', '7711fa12cacdde1450b8edee54de514a');
define('PROPERLY_EXPENSE_TYPE_FIXED', 1);
define('PROPERLY_EXPENSE_TYPE_VARIABLE', 2);
